config/routes.rb
Rails.application.routes.draw do
  root 'midis#new'

  resources :midis, only: [:new, :create, :show]
end

app/models/midi.rb
class Midi < ActiveRecord::Base
  extend Dragonfly::Model::Validations

  VALID_EXTENSIONS = %w(
    mid
    midi
  )

  validates :name, :file, presence: true

  validates_property :ext, of: :file, in: VALID_EXTENSIONS

  dragonfly_accessor :file

  def munged_format
    read_attribute(:munged_format) || { name: name }.merge(MidiMunge::Formatter.new(file.file).format).tap do |format|
      update_attributes(munged_format: format)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/midis_controller.rb
class MidisController < ApplicationController
  def new
    @midi = Midi.new
  end

  def create
    @midi = Midi.new(midi_params)

    if midi.save
      redirect_to midi, notice: 'MIDI uploaded and munged!'
    else
      flash.now[:error] = midi.errors.full_messages.join('; ')
      render 'new'
    end
  end

  def show
    respond_to do |format|
      format.html {}
      format.json { render json: midi.munged_format }
    end
  end

  private

  def midi_params
    params.require(:midi).permit(:name, :file, :file_url)
  end

  def midi
    @midi ||= Midi.find(params[:id])
  end
  helper_method :midi

  def midis
    @midis ||= Midi.last(10)
  end
  helper_method :midis
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MidiMunge</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/midis/new.html.erb
<h1>Enter a URL or Upload a MIDI File</h1>

<%= simple_form_for midi do |f| %>
  <%= f.input :name %>
  <%= f.file_field :file %>
  <%= f.input :file_url, as: :string %>

  <%= f.submit 'Munge!' %>
<% end %>

<h2>Latest Munged MIDIs</h2>
<ul>
  <% midis.each do |m| %>
    <li><%= link_to m.name, m %></li>
  <% end %>
</ul>

app/views/midis/show.html.erb
<h1><%= midi.name %></h1>
<p><%= link_to 'Pure JSON', midi_path(midi, format: :json) %></p>
<p><%= link_to 'Home', new_midi_path %></p>
<div>
  <%= simple_format JSON.pretty_generate(midi.munged_format) unless midi.munged_format.nil? %>
</div>